### ISSUE TITLE
how to extract markdown from uniorg

### ISSUE THREAD

**Issue by zcaudate** [rasendubi/uniorg#2]
this is due to my lack of understanding of unified but I'm not sure why this pipeline errors:

```js
const unified = require("unified");
const parse = require("uniorg-parse");
const uniorg2rehype = require("uniorg-rehype");
const rehype2remark = require("rehype-remark");
const stringify = require("remark-stringify");

function extract_readme(s) {
  return unified()
    .use(parse)
    .use(uniorg2rehype)
    .use(rehype2remark)
    .use(stringify)
    .process(s);
}

extract_readme("* HELLO WORLD");
```

gives this error:

```

uniorg_parser/build/node_modules/unified/index.js:462
    throw new Error('Expected node, got `' + node + '`')
          ^

Error: Expected node, got `[object Object]`
    at assertNode (uniorg_parser/build/node_modules/unified/index.js:462:11)
    at Function.stringify (build/node_modules/unified/index.js:348:5)
    at pipelineStringify (uniorg_parser/build/node_modules/unified/index.js:41:18)
    at wrapped (uniorg_parser/build/node_modules/trough/wrap.js:25:19)
    at next (uniorg_parser/build/node_modules/trough/index.js:57:24)
    at done (uniorg_parser/build/node_modules/trough/wrap.js:55:16)
    at done (uniorg_parser/build/node_modules/unified/index.js:35:7)
    at done (uniorg_parser/build/node_modules/unified/index.js:314:11)
    at next (uniorg_parser/build/node_modules/trough/index.js:59:14)
    at done (uniorg_parser/build/node_modules/trough/wrap.js:55:16)
```

**Comment by rasendubi** [comment]
The issue is rehype-remark returning an array instead of a root node (as remark-stringify expects). I believe this is caused by uniorg-rehype returning a div fragment, not a full html document.

You can use rehype-document to wrap the rehype in html>body.

The following works for me:
```js
const unified = require("unified");
const parse = require("uniorg-parse");
const uniorg2rehype = require("uniorg-rehype");
const rehype2remark = require("rehype-remark");
const stringify = require("remark-stringify");
const document = require("rehype-document");

const processor = unified()
      .use(parse)
      .use(uniorg2rehype)
      .use(document)
      .use(rehype2remark)
      .use(stringify);

function extract_readme(s) {
  return processor.processSync(s).contents;
}

console.log(extract_readme("* HELLO WORLD"));
```

**Comment by zcaudate** [comment]
oh thanks heaps for the explanation. how are you debugging these error messages btw or are you purely going by experience?

**Comment by rasendubi** [comment]
For this one, I ran `parse` and `run` stages separately (without stringify) and then inspected result.

Here is a debug function you can reuse:
```
const processor = unified()
      .use(parse)
      .use(uniorg2rehype)
      .use(document)
      .use(rehype2remark)
      .use(stringify);

function debug(processor, input) {
  console.log("input:", JSON.stringify(input, null, 2));
  let node = processor.parse(input);
  console.log("parse:", JSON.stringify(node, null, 2));
  node = processor.runSync(node);
  console.log("run:", JSON.stringify(node, null, 2));
  const result = processor.stringify(node);
  console.log("stringify:", JSON.stringify(result, null, 2));
  return result;
}

debug(processor, "* HELLO WORLD");
```

**Comment by zcaudate** [comment]
brilliant. that makes a lot of sense. thank you!
